framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: acme/jashca

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # use RedisTagAwareAdapter by default
        # cf. https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#working-with-tags
        app: cache.adapter.redis_tag_aware
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'

        # Namespaced pools use the above "app" backend by default
        pools:
            # Custom cache pools:
            # Doctrine cache pools:
            doctrine.metadata_cache_pool:
                adapter: cache.app
            doctrine.query_cache_pool:
                adapter: cache.app
            doctrine.result_cache_pool:
                adapter: cache.app
